[versions]
androidCoreKtx = "1.9.0"
agp = "7.4.2"
compose = "1.3.1"
kotlin = "1.8.10"
sqlDelight = "1.5.5"
workManager = "2.7.1"
timber = "5.0.1"
leakCanary = "2.10"

[libraries]
androidCoreKtx = { module = "androidx.core:core-ktx", version.ref = "androidCoreKtx" }
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose"}
workManager = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber"}
leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
sqlDelight = { id = "com.squareup.sqldelight", version.ref = "sqlDelight" }
