name: Android Pull Request & Master CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  lint:
    name: Run linter
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Linting
        run: bash ./gradlew lint

  test:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Unit tests
        run: bash ./gradlew test

  instrumented-tests:
    name: Run Instrumented Tests
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew :presentation:connectedAndroidTest

  apk:
    name: Generate APK
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build debug APK
        run: bash ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk